### ISSUE TITLE
API manager - swagger. Not working after installations

### ISSUE THREAD

**Issue by fsalom** [onesaitplatform/onesait-cloud-platform-community-deploy#5]
Hi, I have followed the video tutorial to deploy onesait. I have an instance running on digitalocean. But after the installation of all the modules, when I try to access Swagger or api manager it doesn't work. The problem seems to be that all these features are pointing to localhost instead of the droplet ip, but I don't have a clue about how to change it.

I have created several ontologies and I will like to try the api manager. Thanks in advance.

Attached you will find some screenshots.

<img width="1431" alt="screenshot-1" src="https://user-images.githubusercontent.com/6815781/71575356-ef14fd00-2aec-11ea-9e21-a98bfda6082a.png">
<img width="1435" alt="screenshot-2" src="https://user-images.githubusercontent.com/6815781/71575384-0bb13500-2aed-11ea-931d-b7dc7d949e0a.png">

**Comment by ebustosm** [comment]
Hi @fsalom 

This problem may be caused because api-manager module is not running or is not configured in the load balancer (nginx).
Could you check if this module is running and  enabled in the nginx.conf file?

You can check if it is running with the command "docker ps"

You can find this file inside nginx-proxy container ("docker exec -it proxy sh" to enter). And then "cat /etc/nginx/nginx.conf"

The line where says "#include /usr/local/conf.d/apimanager.conf;" should be un-commented.

Thank you.

**Comment by fsalom** [comment]
Hi @ebustosm,

I didn't have the line un-commented. Now I have it and I have deployed all the services but I still have the same issue

<img width="721" alt="Captura de pantalla 2019-12-30 a las 13 09 26" src="https://user-images.githubusercontent.com/6815781/71581529-ea107780-2b05-11ea-881d-50f60f7ec76f.png">

Services docker ps:
<img width="1429" alt="Captura de pantalla 2019-12-30 a las 13 09 39" src="https://user-images.githubusercontent.com/6815781/71581546-f8f72a00-2b05-11ea-8bbf-d4001dc72dd2.png">

Thank you ;)
